version: "3.7"
services:
  go-torrent-crawler:
    image: go_torrent_crawler
    container_name: go-torrent-crawler
    build:
      context: .
      dockerfile: Dockerfile
    command: /GoTorrentCrawler/TorrentCrawler
    restart: always
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - "./config.json:/config.json:ro"
